## Homework3:
1. Go to your favorite actress'/actor's imdb page
2. Get all the links to his person's movies
3. Get each movie's name, director and imdb score

In [1]:
import requests
from bs4 import BeautifulSoup
from urllib.parse import urljoin
import pandas as pd

## 1. Go to your favorite actress'/actor's imdb page

In [2]:
#THE 211 BEST NETFLIX SERIES
base_site = "https://editorial.rottentomatoes.com/guide/best-netflix-shows-and-movies-to-binge-watch-now/"

response = requests.get(base_site)
response.status_code

200

In [3]:
html = response.content
soup = BeautifulSoup(html, "lxml")

## 2. Get all the links to his person's movies

In [4]:
raw = soup.find_all("div",{"class":"article_movie_title"})

In [5]:
len(raw)

211

In [6]:
links = [i.find("a").get("href") for i in raw]

In [7]:
len(links)

211

In [8]:
links_ordered = ["https:"+ i for i in links]
links_ordered

['https://www.rottentomatoes.com/tv/anne',
 'https://www.rottentomatoes.com/tv/derek',
 'https://www.rottentomatoes.com/tv/ratched',
 'https://www.rottentomatoes.com/tv/behind_her_eyes',
 'https://www.rottentomatoes.com/tv/bloodline',
 'https://www.rottentomatoes.com/tv/emily_in_paris',
 'https://www.rottentomatoes.com/tv/white_lines',
 'https://www.rottentomatoes.com/tv/marvel_s_the_punisher',
 'https://www.rottentomatoes.com/tv/the_duchess',
 'https://www.rottentomatoes.com/tv/lilyhammer',
 'https://www.rottentomatoes.com/tv/halston',
 'https://www.rottentomatoes.com/tv/disenchantment',
 'https://www.rottentomatoes.com/tv/marco_polo',
 'https://www.rottentomatoes.com/tv/grand_army',
 'https://www.rottentomatoes.com/tv/killer_inside_the_mind_of_aaron_hernandez_2020',
 'https://www.rottentomatoes.com/tv/cursed',
 'https://www.rottentomatoes.com/tv/fear_city_new_york_vs_the_mafia',
 'https://www.rottentomatoes.com/tv/self_made_inspired_by_the_life_of_madam_cj_walker',
 'https://www.rottentomatoes.com/tv/love_is_blind',
 'https://www.rottentomatoes.com/tv/ginny_georgia',
 'https://www.rottentomatoes.com/tv/warrior_nun',
 'https://www.rottentomatoes.com/tv/the_eddy',
 'https://www.rottentomatoes.com/tv/the_witcher',
 'https://www.rottentomatoes.com/tv/pacific_rim_the_black',
 'https://www.rottentomatoes.com/tv/the_liberator',
 'https://www.rottentomatoes.com/tv/dark_tourist',
 'https://www.rottentomatoes.com/tv/history_of_swear_words',
 'https://www.rottentomatoes.com/tv/marcella',
 'https://www.rottentomatoes.com/tv/the_serpent',
 'https://www.rottentomatoes.com/tv/daybreak',
 'https://www.rottentomatoes.com/tv/bonding',
 'https://www.rottentomatoes.com/tv/requiem',
 'https://www.rottentomatoes.com/tv/troy_fall_of_a_city',
 'https://www.rottentomatoes.com/tv/safe',
 'https://www.rottentomatoes.com/tv/wanderlust',
 'https://www.rottentomatoes.com/tv/dracula_2020',
 'https://www.rottentomatoes.com/tv/designated_survivor',
 'https://www.rottentomatoes.com/tv/japan_sinks_2020',
 'https://www.rottentomatoes.com/tv/everything_sucks_',
 'https://www.rottentomatoes.com/tv/night_stalker_the_hunt_for_a_serial_killer',
 'https:https://www.rottentomatoes.com/tv/watership_down/s01',
 'https://www.rottentomatoes.com/tv/arrested_development',
 'https://www.rottentomatoes.com/tv/dota_dragons_blood',
 'https://www.rottentomatoes.com/tv/after_life',
 'https://www.rottentomatoes.com/tv/altered_carbon',
 'https://www.rottentomatoes.com/tv/high_score',
 'https://www.rottentomatoes.com/tv/sacred_games',
 'https://www.rottentomatoes.com/tv/lost_in_space',
 'https://www.rottentomatoes.com/tv/colin_in_black_and_white',
 'https://www.rottentomatoes.com/tv/unsolved_mysteries_2020',
 'https://www.rottentomatoes.com/tv/locke_key',
 'https://www.rottentomatoes.com/tv/house-of-cards',
 'https://www.rottentomatoes.com/tv/outer_banks',
 'https://www.rottentomatoes.com/tv/seven_seconds',
 'https://www.rottentomatoes.com/tv/she_s_gotta_have_it',
 'https://www.rottentomatoes.com/tv/marvel_s_the_defenders',
 'https://www.rottentomatoes.com/tv/chelsea_does',
 'https://www.rottentomatoes.com/tv/black_earth_rising',
 'https://www.rottentomatoes.com/tv/the_irregulars',
 'https://www.rottentomatoes.com/tv/collateral',
 'https://www.rottentomatoes.com/tv/bombay_begums',
 'https://www.rottentomatoes.com/tv/hit_and_run',
 'https://www.rottentomatoes.com/tv/dave_chappelle',
 'https://www.rottentomatoes.com/tv/evil_genius_the_true_story_of_america_s_most_diabolical_bank_heist',
 'https://www.rottentomatoes.com/tv/living_with_yourself',
 'https://www.rottentomatoes.com/tv/this_is_a_robbery_the_worlds_biggest_art_heist',
 'https://www.rottentomatoes.com/tv/the_break_with_michelle_wolf',
 'https://www.rottentomatoes.com/tv/tidying_up_with_marie_kondo',
 'https://www.rottentomatoes.com/tv/love_death_robots',
 'https://www.rottentomatoes.com/tv/stateless',
 'https://www.rottentomatoes.com/tv/the_get_down',
 'https://www.rottentomatoes.com/tv/ozark',
 'https://www.rottentomatoes.com/tv/chilling_adventures_of_sabrina',
 'https://www.rottentomatoes.com/tv/jeffrey_epstein_filthy_rich',
 'https://www.rottentomatoes.com/tv/wu_assassins',
 'https://www.rottentomatoes.com/tv/the_stranger',
 'https://www.rottentomatoes.com/tv/raising_dion',
 'https://www.rottentomatoes.com/tv/brand_new_cherry_flavor',
 'https://www.rottentomatoes.com/tv/godless',
 'https://www.rottentomatoes.com/tv/the_umbrella_academy',
 'https://www.rottentomatoes.com/tv/jessica_jones',
 'https://www.rottentomatoes.com/tv/challenger_the_final_flight',
 'https://www.rottentomatoes.com/tv/making_a_murderer',
 'https://www.rottentomatoes.com/tv/wet_hot_american_summer',
 'https://www.rottentomatoes.com/tv/the_oa',
 'https://www.rottentomatoes.com/tv/maniac',
 'https://www.rottentomatoes.com/tv/black_mirror',
 'https://www.rottentomatoes.com/tv/narcos_mexico',
 'https://www.rottentomatoes.com/tv/the_chair_2021',
 'https://www.rottentomatoes.com/tv/tiger_king',
 'https://www.rottentomatoes.com/tv/the_society',
 'https://www.rottentomatoes.com/tv/the_innocents',
 'https://www.rottentomatoes.com/tv/the_spy',
 'https://www.rottentomatoes.com/tv/i_am_not_okay_with_this',
 'https://www.rottentomatoes.com/tv/sense8',
 'https://www.rottentomatoes.com/tv/f_is_for_family',
 'https://www.rottentomatoes.com/tv/atypical',
 'https:https://www.rottentomatoes.com/tv/gilmore-girls/s08',
 'https://www.rottentomatoes.com/tv/the_haunting_of_bly_manor',
 'https://www.rottentomatoes.com/tv/luke_cage',
 'https://www.rottentomatoes.com/tv/ghoul',
 'https://www.rottentomatoes.com/tv/murder_among_the_mormons',
 'https://www.rottentomatoes.com/tv/longmire',
 'https://www.rottentomatoes.com/tv/the_dark_crystal_age_of_resistance',
 'https://www.rottentomatoes.com/tv/shadow_and_bone',
 'https://www.rottentomatoes.com/tv/grace_and_frankie',
 'https://www.rottentomatoes.com/tv/bridgerton',
 'https://www.rottentomatoes.com/tv/lucifer',
 'https://www.rottentomatoes.com/tv/black_summer',
 'https://www.rottentomatoes.com/tv/with_bob_and_david',
 'https://www.rottentomatoes.com/tv/midnight_mass',
 'https://www.rottentomatoes.com/tv/dead_to_me',
 'https://www.rottentomatoes.com/tv/narcos',
 'https://www.rottentomatoes.com/tv/santa_clarita_diet',
 'https://www.rottentomatoes.com/tv/bling_empire',
 'https://www.rottentomatoes.com/tv/easy',
 'https://www.rottentomatoes.com/tv/wormwood',
 'https://www.rottentomatoes.com/tv/orange_is_the_new_black',
 'https://www.rottentomatoes.com/tv/the_crown',
 'https://www.rottentomatoes.com/tv/we_are_the_brooklyn_saints',
 'https://www.rottentomatoes.com/tv/the_devil_next_door-2019',
 'https://www.rottentomatoes.com/tv/queen_sono',
 'https://www.rottentomatoes.com/tv/pretend_its_a_city',
 'https://www.rottentomatoes.com/tv/the_midnight_gospel',
 'https://www.rottentomatoes.com/tv/the_last_kingdom',
 'https://www.rottentomatoes.com/tv/sky_rojo',
 'https://www.rottentomatoes.com/tv/tribes_of_europa',
 'https://www.rottentomatoes.com/tv/dating_around',
 'https://www.rottentomatoes.com/tv/medical_police',
 'https://www.rottentomatoes.com/tv/gentefied',
 'https://www.rottentomatoes.com/tv/naomi_osaka',
 'https://www.rottentomatoes.com/tv/money_heist',
 'https://www.rottentomatoes.com/tv/criminal',
 'https://www.rottentomatoes.com/tv/peaky_blinders',
 'https://www.rottentomatoes.com/tv/you',
 'https://www.rottentomatoes.com/tv/daredevil',
 'https://www.rottentomatoes.com/tv/glow',
 'https://www.rottentomatoes.com/tv/julie_and_the_phantoms',
 'https://www.rottentomatoes.com/tv/yasuke',
 'https://www.rottentomatoes.com/tv/our_planet',
 'https://www.rottentomatoes.com/tv/on_my_block',
 'https://www.rottentomatoes.com/tv/the_kominsky_method',
 'https://www.rottentomatoes.com/tv/squid_game',
 'https://www.rottentomatoes.com/tv/bodyguard',
 'https://www.rottentomatoes.com/tv/the_end_of_the_f_ing_world',
 'https://www.rottentomatoes.com/tv/queer_eye_2018',
 'https://www.rottentomatoes.com/tv/the_haunting_of_hill_house',
 'https://www.rottentomatoes.com/tv/cobra_kai',
 'https://www.rottentomatoes.com/tv/master_of_none',
 'https://www.rottentomatoes.com/tv/bojack_horseman',
 'https://www.rottentomatoes.com/tv/stranger_things',
 'https://www.rottentomatoes.com/tv/teenage_bounty_hunters',
 'https://www.rottentomatoes.com/tv/the_staircase',
 'https://www.rottentomatoes.com/tv/last_chance_u',
 'https://www.rottentomatoes.com/tv/masters_of_the_universe_revelation',
 'https://www.rottentomatoes.com/tv/castlevania',
 'https://www.rottentomatoes.com/tv/love',
 'https://www.rottentomatoes.com/tv/rhythm_flow',
 'https://www.rottentomatoes.com/tv/waffles_mochi',
 'https://www.rottentomatoes.com/tv/flint_town',
 'https://www.rottentomatoes.com/tv/bobby_kennedy_for_president',
 'https://www.rottentomatoes.com/tv/never_have_i_ever',
 'https://www.rottentomatoes.com/tv/dark',
 'https://www.rottentomatoes.com/tv/dear_white_people',
 'https://www.rottentomatoes.com/tv/kingdom_2019',
 'https://www.rottentomatoes.com/tv/unorthodox',
 'https://www.rottentomatoes.com/tv/the_queens_gambit',
 'https://www.rottentomatoes.com/tv/a_series_of_unfortunate_events',
 'https://www.rottentomatoes.com/tv/unbreakable_kimmy_schmidt',
 'https://www.rottentomatoes.com/tv/sex_education',
 'https://www.rottentomatoes.com/tv/call_my_agent',
 'https://www.rottentomatoes.com/tv/cheer',
 'https://www.rottentomatoes.com/tv/the_keepers',
 'https://www.rottentomatoes.com/tv/elite',
 'https://www.rottentomatoes.com/tv/maid',
 'https://www.rottentomatoes.com/tv/lady_dynamite',
 'https://www.rottentomatoes.com/tv/lupin',
 'https://www.rottentomatoes.com/tv/she_ra_and_the_princesses_of_power',
 'https://www.rottentomatoes.com/tv/when_they_see_us',
 'https://www.rottentomatoes.com/tv/russian_doll',
 'https://www.rottentomatoes.com/tv/mindhunter',
 'https://www.rottentomatoes.com/tv/special',
 'https://www.rottentomatoes.com/tv/nailed_it',
 'https://www.rottentomatoes.com/tv/lovesick',
 'https://www.rottentomatoes.com/tv/five_came_back',
 'https://www.rottentomatoes.com/tv/wild_wild_country',
 'https://www.rottentomatoes.com/tv/i_think_you_should_leave_with_tim_robinson',
 'https://www.rottentomatoes.com/tv/sweet_tooth',
 'https://www.rottentomatoes.com/tv/unbelievable',
 'https://www.rottentomatoes.com/tv/american_vandal',
 'https://www.rottentomatoes.com/tv/alias_grace',
 'https://www.rottentomatoes.com/tv/tuca_and_bertie',
 'https://www.rottentomatoes.com/tv/big_mouth',
 'https://www.rottentomatoes.com/tv/one_day_at_a_time',
 'https://www.rottentomatoes.com/tv/nadiya_bakes',
 'https://www.rottentomatoes.com/tv/tales_of_the_city',
 'https://www.rottentomatoes.com/tv/amend_the_fight_for_america',
 'https://www.rottentomatoes.com/tv/maya_and_the_three',
 'https://www.rottentomatoes.com/tv/crazyhead',
 'https://www.rottentomatoes.com/tv/middleditch_and_schwartz',
 'https://www.rottentomatoes.com/tv/lenox_hill',
 'https://www.rottentomatoes.com/tv/the_confession_killer',
 'https://www.rottentomatoes.com/tv/blood_of_zeus',
 'https://www.rottentomatoes.com/tv/dirty_money',
 'https://www.rottentomatoes.com/tv/immigration_nation',
 'https://www.rottentomatoes.com/tv/giri_haji',
 'https://www.rottentomatoes.com/tv/ugly_delicious',
 'https://www.rottentomatoes.com/tv/dash_lily',
 'https://www.rottentomatoes.com/tv/mystery_science_theater_3000_the_return',
 'https://www.rottentomatoes.com/tv/feel_good',
 'https://www.rottentomatoes.com/tv/the_baby_sitters_club_2020']

## 3. Get each movie's name, director and imdb score

### Names

In [9]:
names = [i.find("a").text for i in raw]

In [11]:
names_df = pd.DataFrame(names, columns = ["Names"])
names_df

                                        Names
0                              Anne With an E
1                                       Derek
2                                     Ratched
3                             Behind Her Eyes
4                                   Bloodline
..                                        ...
206                            Ugly Delicious
207                               Dash & Lily
208  Mystery Science Theater 3000: The Return
209                                 Feel Good
210                     The Baby-Sitters Club

[211 rows x 1 columns]

### Years

In [22]:
years = [i.find("span",{"class":"subtle start-year"} ).text.strip("()") for i in raw]

In [23]:
years_df = pd.DataFrame(years, columns = ["Years"] )
years_df

    Years
0    2017
1    2013
2    2020
3    2021
4    2015
..    ...
206  2018
207  2020
208  2017
209  2020
210  2020

[211 rows x 1 columns]

### Scores

In [15]:
scores = ["%"+i.find("span",{"class","tMeterScore"} ).text[:-1] for i in raw]

In [28]:
scores_df = pd.DataFrame(scores, columns = ["Scores"])
scores_df

    Scores
0      %60
1      %60
2      %61
3      %62
4      %62
..     ...
206   %100
207   %100
208   %100
209   %100
210   %100

[211 rows x 1 columns]

In [30]:
xx = pd.concat([names_df, years_df, scores_df], axis = 1)
xx

                                        Names Years Scores
0                              Anne With an E  2017    %60
1                                       Derek  2013    %60
2                                     Ratched  2020    %61
3                             Behind Her Eyes  2021    %62
4                                   Bloodline  2015    %62
..                                        ...   ...    ...
206                            Ugly Delicious  2018   %100
207                               Dash & Lily  2020   %100
208  Mystery Science Theater 3000: The Return  2017   %100
209                                 Feel Good  2020   %100
210                     The Baby-Sitters Club  2020   %100

[211 rows x 3 columns]

In [32]:
xx = xx[["Scores", "Names", "Years"]]

In [33]:
xx

    Scores                                     Names Years
0      %60                            Anne With an E  2017
1      %60                                     Derek  2013
2      %61                                   Ratched  2020
3      %62                           Behind Her Eyes  2021
4      %62                                 Bloodline  2015
..     ...                                       ...   ...
206   %100                            Ugly Delicious  2018
207   %100                               Dash & Lily  2020
208   %100  Mystery Science Theater 3000: The Return  2017
209   %100                                 Feel Good  2020
210   %100                     The Baby-Sitters Club  2020

[211 rows x 3 columns]